apiVersion: v1
kind: ConfigMap
metadata:
  name: visionhub-backend-config
  labels:
    app: visionhub-backend
data:
  APP_NAME: {{ .Values.app.name | quote }}
  DEBUG: {{ .Values.app.debug | quote }}
  JWT_ALGORITHM: {{ .Values.app.jwtAlgorithm | quote }}
  JWT_EXPIRATION_MINUTES: {{ .Values.app.jwtExpirationMinutes | quote }}
  S3_ENDPOINT: {{ .Values.s3.endpoint | quote }}
  S3_BUCKET: {{ .Values.s3.bucket | quote }}
  S3_PUBLIC_URL: {{ .Values.s3.publicUrl | quote }}