apiVersion: apps/v1
kind: Deployment
metadata:
  name: visionhub-backend
  labels:
    app: visionhub-backend
    environment: {{ .Values.environment }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: visionhub-backend
  template:
    metadata:
      labels:
        app: visionhub-backend
        environment: {{ .Values.environment }}
    spec:
      imagePullSecrets:
      - name: thalassa-registry
      
      containers:
      - name: backend
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: http
          containerPort: {{ .Values.service.port }}
          protocol: TCP
        
        envFrom:
        - configMapRef:
            name: visionhub-backend-config
        - secretRef:
            name: visionhub-backend-secrets
        
        resources:
          {{- toYaml .Values.resources | nindent 10 }}