# Image
image:
  repository: registry.nl-01.thalassa.cloud/visionhub-dev/visionhub-frontend
  tag: dev-latest
  pullPolicy: Always

# Replicas
replicas: 1

# Environment
environment: dev

# Service
service:
  type: ClusterIP
  port: 80

# Ingress
ingress:
  enabled: true
  host: visionhub-dev.europecloudatlas.com
  tlsSecretName: visionhub-dev-tls

# Resources
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi